#!/bin/bash

#PBD -N train_200-7
#PBS -l walltime=08:00:00
#PBS -l ncpus=8
#PBS -l mem=64GB
#PBS -l ngpus=1
#PBS -e train_200-7.err
#PBS -o train_200-7.out
#PBS -q ee
#PBS -M 23594292@sun.ac.za
#PBS -m abe

cd /home/23594292/project/model_training
module load app/pytorch/1.13

python3 ../edited_SeqPredNN/train_model.py -r 0.7 -t ../test_set_15.txt -e 200 ../features balanced -o epoch_training_200-7
