#!/bin/bash

#PBS -N bu-train_300-8
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=8:mem=64GB:ngpus=1:Qlist=ee
#PBS -e train_300-8.err
#PBS -o train_300-8.out
#PBS -M 23594292@sun.ac.za
#PBS -m abe

cd /home/23594292/project/balanced_unweighted_models
module load app/pytorch/1.13

python3 ../edited_unweighted_SeqPredNN/train_model.py -t ../test_set_10.txt -e 300 ../features balanced -o epoch_training_300-8 -v ../unbalanced_weighted_models/epoch_training_300-8/validation_set.npz

