#!/bin/bash

#PBS -N us-train_200-8
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=8:mem=64GB:ngpus=1:Qlist=ee
#PBS -e train_200-8.err
#PBS -o train_200-8.out
#PBS -M 23594292@sun.ac.za
#PBS -m abe

cd /home/23594292/project/model_comparisons/undersampled_models
module load app/pytorch/1.13

python3 /home/23594292/project/SeqPredNN-OVERSAMPLING/SeqPredNN/train_model.py -t /home/23594292/project/test_set_10.txt -e 200 /home/23594292/project/features undersample -o epoch_training_200-8 -v /home/23594292/project/model_comparisons/unbalanced_weighted_models/epoch_training_200-8/validation_set.npz
