#!/bin/bash

#PBS -N bu-train_500-8
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=8:mem=64GB:ngpus=1:Qlist=ee
#PBS -e train_500-8.err
#PBS -o train_500-8.out
#PBS -M 23594292@sun.ac.za
#PBS -m abe

cd /home/23594292/project/balanced_unweighted_models
module load app/pytorch/1.13

python3 ../edited_unweighted_SeqPredNN/train_model.py -t ../test_set_10.txt -e 500 ../features balanced -o epoch_training_500-8 -v ../unbalanced_weighted_models/epoch_training_500-8/validation_set.npz

