#!/bin/bash

#PBS -N uu-train_200-6
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=8:mem=64GB:ngpus=1:Qlist=ee
#PBS -e train_200-6.err
#PBS -o train_200-6.out
#PBS -M 23594292@sun.ac.za
#PBS -m abe

cd /home/23594292/project/unbalanced_unweighted_models
module load app/pytorch/1.13

python3 ../edited_unweighted_SeqPredNN/train_model.py -t ../test_set_20.txt -e 200 ../features unbalanced -o epoch_training_200-6 -v ../unbalanced_weighted_models/epoch_training_200-6/validation_set.npz

